storages:
  starscream:
    force_destroy: true
  kepler:
    force_destroy: true

catalogs:
  main:
    name: starscream
    storage: starscream
    force_destroy: true
    permissions:
      - group: one-env-laboratory-sudoers
        privileges: [ALL_PRIVILEGES]
      - group: one-env-laboratory-readers
        privileges: [USE_CATALOG]
    owner: one-env-laboratory-sudoers
  kepler:
    name: kepler
    storage: kepler
    force_destroy: true
    permissions:
      - group: one-env-laboratory-sudoers
        privileges: [ALL_PRIVILEGES]
      - group: one-env-laboratory-readers
        privileges: [USE_CATALOG]
    owner: one-env-laboratory-sudoers

schemas:
  main:
    catalog_name: kepler
    force_destroy: true
    permissions:
      - group: one-env-laboratory-sudoers
        privileges: [ALL_PRIVILEGES]
      - group: one-env-laboratory-readers
        privileges: [USE_SCHEMA, SELECT]
    owner: one-env-laboratory-sudoers
  stars:
    catalog_name: kepler
    force_destroy: true
    permissions:
      - group: one-env-laboratory-sudoers
        privileges: [ALL_PRIVILEGES]
      - group: one-env-laboratory-readers
        privileges: [USE_SCHEMA, SELECT]
    owner: one-env-laboratory-sudoers

volumes:
  probes:
    catalog_name: kepler
    schema_name: main
    force_destroy: true
    permissions:
      - group: one-env-laboratory-sudoers
        privileges: [ALL_PRIVILEGES]
      - group: one-env-laboratory-readers
        privileges: [READ_VOLUME]
    owner: one-env-laboratory-sudoers
  rovers:
    catalog_name: kepler
    schema_name: main
    force_destroy: true
    permissions:
      - group: one-env-laboratory-sudoers
        privileges: [ALL_PRIVILEGES]
      - group: one-env-laboratory-readers
        privileges: [READ_VOLUME]
    owner: one-env-laboratory-sudoers
