storages:
  starscream:
    force_destroy: true
  kepler:
    force_destroy: true

catalogs:
  main:
    name: starscream
    storage: starscream
    force_destroy: true
    permissions: []
    owner: one-env-laboratory-sudoers
  kepler:
    name: kepler
    storage: kepler
    force_destroy: true
    permissions: []
    owner: one-env-laboratory-sudoers

schemas:
  main:
    catalog_name: kepler
    force_destroy: true
    permissions: []
    owner: one-env-laboratory-sudoers
  stars:
    catalog_name: kepler
    force_destroy: true
    permissions: []
    owner: one-env-laboratory-sudoers

volumes:
  probes:
    catalog_name: kepler
    schema_name: main
    force_destroy: true
    permissions:
      - group: one-env-laboratory-sudoers
        privileges: [ALL_PRIVILEGES]
  rovers:
    catalog_name: kepler
    schema_name: main
    force_destroy: true
    permissions:
      - group: one-env-laboratory-sudoers
        privileges: [ALL_PRIVILEGES]
