storages:
  voyager:
    force_destroy: true
  triangulum:
    force_destroy: true

catalogs:
  main:
    name: voyager
    force_destroy: true
    storage: voyager
    permissions:
      - group: one-env-laboratory-sudoers
        privileges: [ALL_PRIVILEGES]
      - group: one-env-laboratory-readers
        privileges: [USE_CATALOG]
    owner: one-env-laboratory-sudoers
  triangulum:
    name: triangulum
    force_destroy: true
    storage: triangulum
    permissions:
      - group: one-env-laboratory-sudoers
        privileges: [ALL_PRIVILEGES]
      - group: one-env-laboratory-readers
        privileges: [USE_CATALOG]
    owner: one-env-laboratory-sudoers

schemas:
  main:
    catalog_name: triangulum
    force_destroy: true
    permissions:
      - group: one-env-laboratory-sudoers
        privileges: [ALL_PRIVILEGES]
      - group: one-env-laboratory-readers
        privileges: [USE_SCHEMA, SELECT]
    owner: one-env-laboratory-sudoers
  stars:
    catalog_name: triangulum
    force_destroy: true
    permissions:
      - group: one-env-laboratory-sudoers
        privileges: [ALL_PRIVILEGES]
      - group: one-env-laboratory-readers
        privileges: [USE_SCHEMA, SELECT]
    owner: one-env-laboratory-sudoers

volumes:
  cloudwatch:
    catalog_name: triangulum
    schema_name: main
    force_destroy: true
    permissions:
      - group: one-env-laboratory-sudoers
        privileges: [ALL_PRIVILEGES]
      - group: one-env-laboratory-readers
        privileges: [READ_VOLUME]
    owner: one-env-laboratory-sudoers
